[package]
name = "vecslice"
description = "Growable slice of a Vec."
version = "0.1.0"
edition = "2021"
authors = ["Liam Garriga <liam@garriga.dev>"]
license = "MIT"
keywords = ["vec", "slice", "vecslice", "growable"]
categories = ["data-structures"]

[dependencies]
